export { useProducts } from './hooks/use-products'
export * from './model/types'
export { ProductCard } from './ui/product-card'
export { ProductGallery } from './ui/product-gallery'
export { ProductsGrid } from './ui/products-grid'
